
## 安装Docker Compose
# curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
# docker-compose --version
# docker-compose up -d
version: '2.4'
networks:
    br0:
      external: true

services:
  express0s:
    container_name: express0s
    #image: chunhui2001/alpine:3.9.node_12.18.3
    image: chunhui2001/alpine:3.9.node_16
    hostname: express0s
    #mem_limit: 300m
    ports:
      - 3000:3000
    #entrypoint: ["/bin/sh", "-c", "while true; do echo 1 >/dev/null 2>/dev/null; sleep 1; done"]
    entrypoint: ["make", "-f", "/express0s/Makefile", "run"]
    volumes:
      - ../express0s:/express0s:rw
    restart: always
    networks:
        br0:
          ipv4_address: 172.16.197.220


